[package]
name = "brain_fuck"
version = "0.1.0"
edition = "2021"

[dependencies]


[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[profile.release.package."*"]
opt-level = 3
codegen-units = 1
incremental = false
debug = false
